# update 2023 war data 
name: manual-war23
on:
  workflow_dispatch:
permissions: write-all
jobs:
  rocket-fig:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements_rockets.txt
    - name: run script
      run: |
        python code/war23_idf_mem.py
    - name: commit files
      run: |
        git config --global user.name "actions"
        git config --global user.email "actions@github"
        git add -A
        git commit -m "manual update"
    - name: pull files
      run: |
        git pull
    - name: push files
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
#
#         wget -O test.txt "https://maps.googleapis.com/maps/api/geocode/json?address=רחובות&key=${{ secrets.GOOMAP }}&language=iw"
#         wc -c test.txt
