# download data and make casualties csv

name: casualties daily

on:
  schedule:
    - cron: '30 6/12 * * *'

permissions: write-all
  # contents: read

jobs:
  casualties:
    runs-on: ubuntu-latest
    environment: rockets
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements_rockets.txt
    - name: run casualties script
      run: |
        python code/war23_casualties.py
    - name: check news
      env:
          OAuth: ${{ secrets.MASTODON_BOT }}
      run: |
        git config --global user.name "actions"
        git config --global user.email "actions@github"
        if [ -n "$(git status --porcelain)" ]; then
          echo "IS_NEW=true" >> $GITHUB_ENV
          # python mastodon_bot.py "new images on https://yuval-harpaz.github.io/astro/news_by_date.html"
        else
          echo "no changes"
          echo "IS_NEW=false" >> $GITHUB_ENV
        fi
    - name: commit files
      run: |
        git add -A
        git commit -m "daily casualties"
        git pull
      if: ${{ env.IS_NEW == 'true' }}
    - name: push files
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ env.IS_NEW == 'true' }}
