# download data and make figures as html using python

name: earthquake map daily

on:
  schedule:
    - cron: '0 */2 * * *'

permissions: write-all
  # contents: read

jobs:
  quake-fig:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: run script
      run: |
        python code/earthquakes1.py
    - name: check news
      env:
        NEWS: ${{ false }}
      run: |
        git config --global user.name "actions"
        git config --global user.email "actions@github"
        if [ -n "$(git status --porcelain)" ]; then
          NEWS = ${{ true }}
        else
          echo "no changes"
        fi
    - name: commit files
      run: |
        git add -A
        git commit -m "earthquake daily update"
        git pull
      if: env.NEWS
    - name: push files
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      if: env.NEWS
