# download data and make figures as html using python

name: alarms daily

on:
  schedule:
    - cron: '10-59/20 * * * *'

permissions: write-all
  # contents: read

jobs:
  alarms-fig:
    runs-on: ubuntu-latest
    environment: rockets
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements_rockets.txt
    - name: run rocket alarms script
      env:
          OAuth: ${{ secrets.GOOMAP }}
      run: |
        python code/alarms3.py
    - name: run rocket 7 days script
      env:
          OAuth: ${{ secrets.GOOMAP }}
      run: |
        python code/alarms_week.py
    - name: run deaths script
      env:
          OAuth: ${{ secrets.GOOMAP }}
      run: |
        python code/scrap_war.py
    - name: check news
      run: |
        git config --global user.name "actions"
        git config --global user.email "actions@github"
        if [ -n "$(git status --porcelain)" ]; then
          echo "IS_NEW=true" >> $GITHUB_ENV
        else
          echo "no changes"
          echo "IS_NEW=false" >> $GITHUB_ENV
        fi
    - name: commit files
      run: |
        git add -A
        git commit -m "daily update"
        git pull
      if: ${{ env.IS_NEW == 'true' }}
    - name: push files
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ env.IS_NEW == 'true' }}
